config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

login/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

app_name = 'login'

urlpatterns = [
    # path('', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('', views.userlogin, name='login'),
    path('logout/', views.userLogout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('welcome/(?<nickname>)', views.welcome, name='welcome'),
    path('cancel/', views.cancel, name='cancel'),
]

login/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, email, nickname, password=None):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=UserManager.normalize_email(email),
            nickname=nickname,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nickname, password):
        u = self.create_user(email=email,
                             nickname=nickname,
                             password=password,
                             )
        u.is_admin = True
        u.save(using=self._db)
        return u

class User(AbstractBaseUser, PermissionsMixin):
    # CHOICE_GENDER = (
    #     ('man', '남성'),
    #     ('woman', '여성')
    # )

    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )

    nickname = models.CharField(
        u'닉네임',
        max_length=30,
        blank=False,
        unique=True,
        default='')

    # gender = models.CharField(max_length=5, choices=CHOICE_GENDER)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)


    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nickname']

    def get_name(self):
        # The user is identified by their email address
        return self.nickname

    def get_email(self):
        # The user is identified by their email address
        return self.email

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class UserForm(UserCreationForm):
    # CHOICE_GENDER = (
    #     ('man', '남자'),
    #     ('woman', '여자')
    # )
    email = forms.EmailField(label='이메일')
    nickname = forms.CharField(max_length=30, label='이름')
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()
    # gender = forms.CharField(label='성별', widget=forms.Select(choices=CHOICE_GENDER))

    class Meta:  # SignupForm에 대한 기술서
        model = User
        fields = ("email", "nickname", "password1", "password2")  # 작성한 필드만큼 화면에 보여짐

    def __init__(self, *args, **kwargs):
        # SignupForm 을 재정의하여 모든 template class 속성을 'form-control' 로 지정
        super(UserForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

# class LoginForm(AuthenticationForm):
class LoginForm(forms.ModelForm):
    # email = forms.EmailField(
    #     widget=forms.EmailInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'email',
    #             'required': 'True',
    #         }
    #     )
    # )
    # password = forms.CharField(
    #     widget=forms.PasswordInput(
    #         attrs={
    #             'class': 'form-control',
    #             'placeholder': 'Password',
    #             'required': 'True',
    #         }
    #     )
    # )
    email = forms.EmailField(label='이메일')
    password = forms.PasswordInput()

    class Meta:
        model = User
        fields = ("email", "password")
        # fields = ['email', 'password']
        # widgets = {
        #     'email': forms.EmailInput(attrs={'class': 'form-control'}),
        #     'password': forms.PasswordInput(attrs={'class': 'form-control'}),
        # }
        # labels = {
        #     'email': '이메일',
        #     'password': '비밀번호',
        # }
    def __init__(self, *args, **kwargs):
        # SignupForm 을 재정의하여 모든 template class 속성을 'form-control' 로 지정
        super(LoginForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

login/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect, reverse, HttpResponseRedirect
from .forms import UserForm, LoginForm

# Create your views here.
def userlogin(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(email=email, password=password)
        # print(user)

        if user is not None:
            # redirect the user to the home page
            login(request, user)
            # print(user.nickname)

            redirect_to = reverse('login:welcome', kwargs={'nickname':user.nickname})
            return HttpResponseRedirect(redirect_to)
        else:
            # display an error message
            error = 'Invalid credentials. Please try again.'

        return redirect('login:welcome')
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form':form})

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            sign = form.save(commit=False)
            email = form.cleaned_data.get('email')
            nickname = form.cleaned_data.get('nickname')
            raw_password = form.cleaned_data.get('password1')
            sign.save()
            user = authenticate(email=email, password=raw_password)
            # print(username)
            if user is not None:
                # redirect the user to the home page
                login(request, user)

                # redirect_to = reverse('login:welcome', kwargs={'nickname':nickname})
                # return HttpResponseRedirect(redirect_to)
                return render(request, 'welcome.html', {'name': nickname})
            else:
                # display an error message
                error = 'Invalid credentials. Please try again.'

            return redirect('login:welcome')
    else:
        form = UserForm()
    # context = {'form':form}
    # return render(request, 'common/signup.html', context)
    return render(request, 'signup.html', {'form':form})

def welcome(request, nickname):
    # error = None
    return render(request, 'welcome.html', {'name': nickname})

def userLogout(request):
    logout(request)
    return redirect('login:login')

def cancel(request):
    return redirect('login:login')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <title>{% block title %}Demo{% endblock %}</title>
</head>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<body>
    <div class="topnav">
        <div class="center">
            <div class="menu">
                <!-- 네비게이션바 -->
                {% include "navbar.html" %}
            </div>
        </div>
    </div>

    <div class="sidemenu">
        <ul>
            <li><a href="{% url 'common:login' %}">home</a></li>
            <li><a href="#">board</a></li>
            <li><a href="#">menu3</a></li>
            <li><a href="#">menu4</a></li>
        </ul>
    </div>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
    <div class="wrap_content">
        <div id="content" name="content" class="container">
        {% block content %}
        {% endblock %}
        </div>
    </div>
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/login/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{field.errors}}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.none_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/login/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}login{% endblock %}</title>

</head>
<body>
<style>
.divider:after,
.divider:before {
content: "";
flex: 1;
height: 1px;
background: #eee;
}
.h-custom {
height: calc(100% - 73px);
}
@media (max-width: 450px) {
.h-custom {
height: 100%;
}
}
</style>
  <section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
            class="img-fluid" alt="Sample image">
          <!--img src="{% static 'img/lenna.bmp' %}" class="img-fluid" alt="Sample image"/-->
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form method="post" action="{% url 'login:login' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" name="email" id="email" class="form-control form-control-lg"
                placeholder="Enter a valid email address" value="{{ form.email.value|default_if_none:'' }}"/>
              <label class="form-label" for="email">Email address</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password" name="password" id="password" class="form-control form-control-lg"
                placeholder="Enter password" value="{{ form.password.value|default_if_none:'' }}"/>
              <label class="form-label" for="password">Password</label>
            </div>

            <div class="d-flex justify-content-between align-items-center">
              <!-- Checkbox -->
              <div class="form-check mb-0">
                <input class="form-check-input me-2" type="checkbox" value="" id="chk_remember" />
                <label class="form-check-label" for="chk_remember">
                  Remember me
                </label>
              </div>
              <a href="#!" class="text-body">Forgot password?</a>
            </div>

            <div class="text-center text-lg-start mt-4 pt-2">
              <button type="submit" class="btn btn-primary btn-lg"  style="padding-left: 2.5rem; padding-right: 2.5rem;">Login</button>
              <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'login:signup' %}"
                  class="link-danger">Register</a></p>
            </div>

          </form>
        </div>
      </div>
    </div>
    <div
      class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
      <!-- Copyright -->
      <div class="text-white mb-3 mb-md-0">
        Copyright © 2023. All rights reserved.
      </div>
    </div>
  </section>
</body>
</html>

templates/login/signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<!DOCTYPE html>
<html lang="en">
<head>
      <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <title>{% block title %}Signin{% endblock %}</title>
</head>
<body>
<style>
.divider:after,
.divider:before {
content: "";
flex: 1;
height: 1px;
background: #eee;
}
.h-custom {
height: calc(100% - 73px);
}
@media (max-width: 450px) {
.h-custom {
height: 100%;
}
}
</style>
  <section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
          <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
            class="img-fluid" alt="Sample image">
        </div>
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
          <form method="post" action="{% url 'login:signup' %}">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="email" name="email" id="email" class="form-control form-control-lg"
                placeholder="Enter a valid email address" value="{{ form.email.value|default_if_none:'' }}"/>
              <label class="form-label" for="email">Email 주소</label>
            </div>


            <div class="form-outline mb-3">
              <input type="text" name="nickname" id="nickname" class="form-control form-control-lg"
                     placeholder="Enter username" value="{{ form.nickname.value|default_if_none:'' }}">
              <label class="form-label" for="nickname">사용자 명</label>
            </div>


            <!-- Password input -->
            <div class="form-outline mb-3">
              <input type="password1" name="password1" id="password1" class="form-control form-control-lg"
                placeholder="Enter password" value="{{ form.password1.value|default_if_none:'' }}"/>
              <label class="form-label" for="password1">비밀번호</label>
            </div>

            <div class="form-outline mb-3">
              <input type="password2" name="password2" id="password2" class="form-control form-control-lg"
                placeholder="Confirm password" value="{{ form.password2.value|default_if_none:'' }}"/>
              <label class="form-label" for="password2">비밀번호 확인</label>
            </div>

            <div class="text-center text-lg-start mt-4 pt-2">
              <button type="submit" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;">가입</button>
              <button type="submit" class="btn btn-primary btn-lg" formaction="{% url 'login:cancel' %}">취소</button>
            </div>

          </form>
        </div>
      </div>
    </div>
    <div
      class="d-flex flex-column flex-md-row text-center text-md-start justify-content-between py-4 px-4 px-xl-5 bg-primary">
      <!-- Copyright -->
      <div class="text-white mb-3 mb-md-0">
        Copyright © 2023. All rights reserved.
      </div>
    </div>
  </section>
</body>
</html>

templates/login/welcome.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <title>Home</title>
</head>
<body>
    <!-- Header -->

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
            <h1 id="site-name"><a class="navbar-brand" href="#">Mysite</a></h1>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarText">
                <strong>{{ name }}님</strong>환영합니다.
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-link active" class="nav-item">
                        <a href="/">사이트 보기</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="...">비밀번호 변경</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login:logout' %}">로그아웃</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- END Header -->
        <div class="main" id="main">
            <p>
                <h1> {{ name }} Hello welcome !! </h1>

            </p>
        </div>
</body>
</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'login:index' %}">증권분석</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated%}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }}(로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>